name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
          extra-platforms = aarch64-linux arm-linux
          boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
    - run: nix-build '<nixpkgs/nixos>' -A config.system.build.sdImage -I nixos-config=./sd-image.nix --argstr system aarch64-linux
    - uses: actions/upload-artifact@v3
      with:
        name: sd-image.img
        path: ./result/sd-image/*.img*

#        nix-build '<nixpkgs/nixos>'  \
#          -A config.system.build.sdImage \
#          -I nixos-config=./configuration.custom.sdImage.nix \
#          --argstr system aarch64-linux \
#          --option sandbox false